
import argparse
def parse():
    parser = argparse.ArgumentParser()
    parser.add_argument('--random_seed', type=int, default=2021, help='随机种子')
    parser.add_argument('--meaning_size', type=int, default=100, help='语义抽取的隐状态大小')
    parser.add_argument('--pretrained_file_folder', type=str, default='./PretrainedEmbedding', help='预训练的静态文件存储位置')
    parser.add_argument('--cache_file', type=bool, default=True, help='是否缓存特征文件')
    parser.add_argument('--overwrite_cached_file', type=bool, default=False, help='是否覆写特征文件')
    parser.add_argument('--dataset_file_folder', type=str, default='./datasets/', help='数据/特征文件所在位置')
    parser.add_argument('--validation_folder', type=int, default=1, help='进行交叉验证的folder数，default=1（没有交叉验证）')
    parser.add_argument('--train_rate', type=float, default=0.6, help='不进行交叉验证的分割比例，只有当validation_folder = 1时有效，default=0.6')
    parser.add_argument('--test_rate', type=float, default=0.2, help='不进行交叉验证的分割比例，只有当validation_folder = 1时有效，default=0.2')
    parser.add_argument('--epochs', type=int, default=30, help='Epoch数')
    parser.add_argument('--echo_per_step', type=int, default=10, help='多少步打印一次')
    parser.add_argument('--batch_size', type=int, default=32, help='batch 大小')
    parser.add_argument('--weight_decay', type=float, default=1e-3, help='weight decay')
    parser.add_argument('--learning_rate', type=float, default=1e-3, help='学习率')
    parser.add_argument('--num_warmup_steps', type=float, default=50, help='warm up steps')
    parser.add_argument('--continue_training', type=bool, default=False, help='是否继续训练')
    parser.add_argument('--model_path', type=str, default=None, help='模型的保存位置')
    parser.add_argument('--devices', type=str, default='cpu', help='模型的运行环境')
    parser.add_argument('--norm_type', type=int, default=2, help='梯度的范数类型')
    parser.add_argument('--max_grad_norm', type=float, default=1e3, help='梯度范数的最大值')
    parser.add_argument('--padding_idx', type=int, default=0, help='padding的index')
    parser.add_argument('--comment_dropout_rate', type=float, default=0.2, help='comment内容的dropout rate')
    parser.add_argument('--comment_context_dropout_rate', type=float, default=0.4, help='所有内容的dropout rate')
    parser.add_argument('--train', type=bool, default=False, help='是否训练')
    parser.add_argument('--eval', type=bool, default=False, help='是否测试')
    parser.add_argument('--early_stop', type=bool, default=False, help='是否使用early stop')
    parser.add_argument('--patience', type=int, default=5, help='patience 是多少')
    parser.add_argument('--pretrained_file_path', type=str, default='', help='预训练模型的路径')
    parser.add_argument('--position_dim', type=int, default=50, help='position embedding的维度')
    parser.add_argument('--position_padding_idx', type=int, default=0, help='position embedding padding的index')
    parser.add_argument('--accumulation_step', type=int, default=1, help='梯度累积的步数')
    parser.add_argument('--mode', type=str, default='glove', help='文本向量的嵌入方法: GloVe or BERT')
    return parser.parse_args()
